# Generated by Django 5.1.6 on 2025-09-16 19:16

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupportKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Support Knowledge Base Data',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerSupportPhoneCall',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('conversation', models.JSONField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('call_sid', models.CharField(max_length=255, unique=True)),
                ('already_seen', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Customer Support Phone Calls',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerSupportKnowledgeBaseChunk',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='customer_support.customersupportknowledgebase')),
            ],
            options={
                'verbose_name_plural': 'Customer Support Knowledge Base Chunks',
                'ordering': ('-updated_at',),
            },
        ),
    ]
