# Generated by Django 5.1.6 on 2025-09-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0002_alter_customersupportknowledgebasechunk_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoDeskTicket',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.CharField(max_length=255, unique=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Zoho Desk Tickets',
                'ordering': ('-updated_at',),
            },
        ),
    ]
