# Generated by Django 5.1.6 on 2025-09-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0003_zohodeskticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersupportknowledgebase',
            name='url',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
